#!/usr/bin/env bash
set -euo pipefail

#
# EstaCoda uninstall script.
#
# Removes the prebuilt binary install: install directory, wrapper symlinks,
# and PATH entries from shell rc files. User data (~/.estacoda) is preserved
# by default.
#
# Usage:
#   bash scripts/uninstall.sh
#

STAMP_PATHS=(
  "$HOME/.estacoda/bin/.install-method.json"
  "/usr/local/lib/estacoda/.install-method.json"
)

INSTALL_STAMP=""
INSTALL_DIR=""

detect_install_dir() {
  for stamp_path in "${STAMP_PATHS[@]}"; do
    if [ -f "$stamp_path" ]; then
      INSTALL_STAMP="$stamp_path"
      INSTALL_DIR=$(grep -o '"installDir"[[:space:]]*:[[:space:]]*"[^"]*"' "$stamp_path" | head -1 | sed 's/.*"\([^"]*\)".*/\1/')
      return 0
    fi
  done

  # Fallback: check well-known locations
  for dir in "$HOME/.estacoda/bin" "/usr/local/lib/estacoda"; do
    if [ -f "$dir/estacoda" ]; then
      INSTALL_DIR="$dir"
      return 0
    fi
  done

  return 1
}

remove_wrappers() {
  local removed=0
  for wrapper in "$HOME/.local/bin/estacoda" "$HOME/.estacoda/bin/estacoda" "/usr/local/bin/estacoda"; do
    if [ -L "$wrapper" ] || [ -f "$wrapper" ]; then
      if [ -L "$wrapper" ]; then
        target=$(readlink "$wrapper" 2>/dev/null || true)
        if echo "$target" | grep -qi "estacoda"; then
          rm -f "$wrapper"
          echo "Removed wrapper: $wrapper"
          removed=$((removed + 1))
        fi
      elif grep -Eq "Generated by scripts/(install|setup-estacoda|install-binary)\\.sh|EstaCoda" "$wrapper" 2>/dev/null; then
        rm -f "$wrapper"
        echo "Removed wrapper: $wrapper"
        removed=$((removed + 1))
      fi
    fi
  done
  if [ "$removed" -eq 0 ]; then
    echo "Wrapper cleanup: no known EstaCoda wrappers found."
  fi
}

cleanup_path_entries() {
  local removed=0
  for rc_file in "$HOME/.bashrc" "$HOME/.zshrc" "$HOME/.profile" "$HOME/.bash_profile"; do
    if [ -f "$rc_file" ]; then
      if grep -q "estacoda" "$rc_file" 2>/dev/null; then
        if sed -n '/Added by EstaCoda installer/p' "$rc_file" 2>/dev/null | grep -q .; then
          sed -i '/Added by EstaCoda installer/d;/estacoda.*PATH/d' "$rc_file"
          echo "Removed PATH entries from: $rc_file"
          removed=$((removed + 1))
        fi
      fi
    fi
  done
  if [ "$removed" -eq 0 ]; then
    echo "PATH cleanup: no EstaCoda shell config entries found."
  fi
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
echo "EstaCoda uninstall"

if detect_install_dir; then
  echo "Install directory: $INSTALL_DIR"
  [ -n "$INSTALL_STAMP" ] && echo "Stamp: $INSTALL_STAMP"

  remove_wrappers
  cleanup_path_entries

  if [ -n "$INSTALL_DIR" ] && [ -d "$INSTALL_DIR" ]; then
    rm -rf "$INSTALL_DIR"
    echo "Removed install directory: $INSTALL_DIR"
  else
    echo "Install directory not found or already removed."
  fi
else
  echo "No EstaCoda binary install found."

  remove_wrappers
  cleanup_path_entries
fi

echo ""
echo "User data preserved: ~/.estacoda"
echo "To remove all data: rm -rf ~/.estacoda"
