#!/usr/bin/env bash
set -euo pipefail

#
# EstaCoda uninstall script.
#
# Detects the install method and runs the appropriate uninstall flow:
#   - binary: removes install dir, wrapper symlinks, PATH entries
#   - managed-source: removes source checkout, wrapper, PATH entries
#   - manual-source: removes wrapper, PATH entries (preserves checkout)
#   - npm/pnpm/homebrew/docker: delegates to package manager
#

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# ---------------------------------------------------------------------------
# Try running the runtime uninstaller if available
# ---------------------------------------------------------------------------
if command -v estacoda >/dev/null 2>&1; then
  exec estacoda uninstall "$@"
fi

if [ -f "$REPO_ROOT/dist/index.js" ]; then
  exec node "$REPO_ROOT/dist/index.js" uninstall "$@"
fi

# ---------------------------------------------------------------------------
# Fallback: detect install method from stamp and handle binary/uninstalled
# ---------------------------------------------------------------------------

# Well-known stamp locations
STAMP_PATHS=(
  "$HOME/.estacoda/bin/.install-method.json"
  "/usr/local/lib/estacoda/.install-method.json"
  "$HOME/.estacoda/estacoda/.install-method.json"
)

detect_install_method() {
  for stamp_path in "${STAMP_PATHS[@]}"; do
    if [ -f "$stamp_path" ]; then
      INSTALL_STAMP="$stamp_path"
      INSTALL_METHOD=$(grep -o '"method"[[:space:]]*:[[:space:]]*"[^"]*"' "$stamp_path" | head -1 | sed 's/.*"\([^"]*\)".*/\1/')
      INSTALL_DIR=$(grep -o '"installDir"[[:space:]]*:[[:space:]]*"[^"]*"' "$stamp_path" | head -1 | sed 's/.*"\([^"]*\)".*/\1/')
      return 0
    fi
  done
  return 1
}

remove_wrappers() {
  local removed=0
  for wrapper in "$HOME/.local/bin/estacoda" "$HOME/.estacoda/bin/estacoda" "/usr/local/bin/estacoda"; do
    if [ -L "$wrapper" ] || [ -f "$wrapper" ]; then
      # Check if it's an EstaCoda wrapper
      if [ -L "$wrapper" ]; then
        target=$(readlink "$wrapper" 2>/dev/null || true)
        if echo "$target" | grep -qi "estacoda"; then
          rm -f "$wrapper"
          echo "Removed wrapper: $wrapper"
          removed=$((removed + 1))
        fi
      elif grep -Eq "Generated by scripts/(install|setup-estacoda|install-binary)\\.sh|EstaCoda" "$wrapper" 2>/dev/null; then
        rm -f "$wrapper"
        echo "Removed wrapper: $wrapper"
        removed=$((removed + 1))
      fi
    fi
  done
  if [ "$removed" -eq 0 ]; then
    echo "Wrapper cleanup: no known EstaCoda wrappers found."
  fi
}

cleanup_path_entries() {
  local removed=0
  for rc_file in "$HOME/.bashrc" "$HOME/.zshrc" "$HOME/.profile" "$HOME/.bash_profile"; do
    if [ -f "$rc_file" ]; then
      if grep -q "estacoda" "$rc_file" 2>/dev/null; then
        # Only remove lines that are clearly EstaCoda PATH additions
        if sed -n '/EstaCoda installer/p;/\.estacoda\/bin.*PATH/p;/\.local\/bin.*estacoda/p' "$rc_file" 2>/dev/null | grep -q .; then
          sed -i '/EstaCoda installer/d;/\.estacoda\/bin.*PATH/d;/\.local\/bin.*estacoda.*PATH/d' "$rc_file"
          echo "Removed PATH entries from: $rc_file"
          removed=$((removed + 1))
        fi
      fi
    fi
  done
  if [ "$removed" -eq 0 ]; then
    echo "PATH cleanup: no EstaCoda shell config entries found."
  fi
}

if detect_install_method; then
  echo "EstaCoda uninstall"
  echo "Detected install method: $INSTALL_METHOD"
  echo "Stamp: $INSTALL_STAMP"

  case "$INSTALL_METHOD" in
    binary)
      remove_wrappers
      cleanup_path_entries

      if [ -n "$INSTALL_DIR" ] && [ -d "$INSTALL_DIR" ]; then
        rm -rf "$INSTALL_DIR"
        echo "Removed binary install directory: $INSTALL_DIR"
      else
        echo "Binary install directory not found or already removed."
      fi
      ;;
    managed-source)
      remove_wrappers
      cleanup_path_entries

      if [ -n "$INSTALL_DIR" ] && [ -d "$INSTALL_DIR" ]; then
        rm -rf "$INSTALL_DIR"
        echo "Removed managed source directory: $INSTALL_DIR"
      fi
      ;;
    manual-source)
      remove_wrappers
      cleanup_path_entries

      if [ -n "$INSTALL_DIR" ] && [ -d "$INSTALL_DIR" ]; then
        echo "Manual source checkout preserved: $INSTALL_DIR"
        echo "Remove manually if no longer needed: rm -rf $INSTALL_DIR"
      fi
      ;;
    *)
      echo ""
      echo "Install method '$INSTALL_METHOD' requires its package manager for uninstall:"
      case "$INSTALL_METHOD" in
        npm-global)   echo "  Run: npm uninstall -g estacoda" ;;
        pnpm-global)  echo "  Run: pnpm remove -g estacoda" ;;
        homebrew)     echo "  Run: brew uninstall estacoda" ;;
        docker)       echo "  Remove container/image manually." ;;
        *)            echo "  Unknown method. Remove manually." ;;
      esac
      ;;
  esac

  echo ""
  echo "User data preserved: ~/.estacoda"
  echo "To remove all data: rm -rf ~/.estacoda"
  exit 0
fi

# ---------------------------------------------------------------------------
# No stamp found — generic guidance
# ---------------------------------------------------------------------------
cat >&2 <<'EOF'
EstaCoda uninstall could not find an installed estacoda command or a build stamp.

If this was a binary install, run:
  rm -rf ~/.estacoda/bin
  rm -f ~/.local/bin/estacoda

If this was an npm install, run:
  npm uninstall -g estacoda

If this was a pnpm install, run:
  pnpm remove -g estacoda

If this was a Homebrew install, run:
  brew uninstall estacoda

For a source checkout, build first with:
  pnpm install --frozen-lockfile
  pnpm run build
  node dist/index.js uninstall
EOF
exit 1
